### ISSUE TITLE
Custom icon not showing up

### ISSUE THREAD

**Issue by albertocrea** [rvalitov/widgetkit-popover-ex#2]
Hi Ramil
Nice idea and work so far.
![captura de pantalla 2016-01-28 a las 12 51 06](https://cloud.githubusercontent.com/assets/1771572/12643667/d78da5d0-c5bd-11e5-9c29-5c0958aa089b.png)
![captura de pantalla 2016-01-28 a las 12 51 01](https://cloud.githubusercontent.com/assets/1771572/12643669/d7bee8ca-c5bd-11e5-890b-bb1e96041669.png)
![captura de pantalla 2016-01-28 a las 12 50 43](https://cloud.githubusercontent.com/assets/1771572/12643668/d7b9f32e-c5bd-11e5-9195-0fe98957564e.png)
![captura de pantalla 2016-01-28 a las 12 50 35](https://cloud.githubusercontent.com/assets/1771572/12643670/d830a7b2-c5bd-11e5-939b-9bca0757eb97.png)

I'm testing the custom pop up icon following your instructions but no image shows up. I'm testing it on salt template with last warp (everything up to date). Any idea about what i'm possibly doing wrong?

**Comment by rvalitov** [comment]
Hi! I see you're testing it in on a localhost? May be it's the reason why you don't see the image. Please, try accessing the website using http://127.0.0.1 or http://localhost - may be one of them will solve this. If yes, then I'll update the code. Also, please, use the "web inspector" in your browser - it should show you the URL of the image that was failed to load. Please, post this URL here.

**Comment by rvalitov** [comment]
This issue should be fixed in the latest release (v.1.1). Please, try installing it and let me know about the results. The Wiki section is also updated, you may find some useful examples there.

**Comment by albertocrea** [comment]
Hi Ramil

Thank you for the update, i will test it and let you know about the outcome.

Kind regards
Alberto
 http://albertocrea.com/Alberto Estévez
albertocrea.com http://albertocrea.com/
info@albertocrea.com mailto:info@albertocrea.com
 https://es.pinterest.com/alberto2806/alberto-ea/ http://twitter.com/albertocrea http://www.facebook.com/alberto.estevezdecastro http://www.albertocrea.com/

**Comment by albertocrea** [comment]
Hi Ramil

I just installed your update but unfortunately it still refuses to show images i refer to using relative paths to the images. This happens on a local server as well as on a live server.
Here you can see how the pop up shows up only if i use absolute paths.

http://merinoarreguiarquitectos.com/demo http://merinoarreguiarquitectos.com/demo

Do you think there is a way to avoid using absolute paths to call the custom images?

As you can imagine i would like to avoid extra path editing each time a move from one server to another.

Thank you Ramil for writing such useful widget extensions. I hadn’t time yet to check you Map widget add on, but i will definitely do this week. I’ll let you know how it worked out for me.

Kind regards en keep on coding nice stuff

Alberto

 http://albertocrea.com/Alberto Estévez
albertocrea.com http://albertocrea.com/
info@albertocrea.com mailto:info@albertocrea.com
 https://es.pinterest.com/alberto2806/alberto-ea/ http://twitter.com/albertocrea http://www.facebook.com/alberto.estevezdecastro http://www.albertocrea.com/
