### ISSUE TITLE
Custom Toggle Image didn`t works

### ISSUE THREAD

**Issue by ProjektOliver** [rvalitov/widgetkit-popover-ex#6]
Hi,
when I set my own Images, they didn`t shown.
[https://www.rappenauer.de/index.php?option=com_content&view=article&id=28](url)

**Comment by rvalitov** [comment]
Hi! Please provide access to Joomla backend to ramilvalitov@gmail.com , so that I can check the settings. Thank you!

**Comment by ProjektOliver** [comment]
Hi, here you can check it:

User: rvalitov
Pass: rvalitov0815

Thank you

Von: Ramil Valitov [mailto:notifications@github.com]
Gesendet: Freitag, 2. Juni 2017 10:24
An: rvalitov/widgetkit-popover-ex <widgetkit-popover-ex@noreply.github.com>
Cc: Oliver OM. Münch <oliver.muench@franz-mediaprint.de>; Author <author@noreply.github.com>
Betreff: Re: [rvalitov/widgetkit-popover-ex] Custom Toggle Image didn`t works (#6)


Hi! Please provide access to Joomla backend to ramilvalitov@gmail.com<mailto:ramilvalitov@gmail.com> , so that I can check the settings. Thank you!

**Comment by rvalitov** [comment]
Please, also specify the URL to access the backend

**Comment by ProjektOliver** [comment]
Ah sorry, I´ve forget it:
http://www.rappenauer.de/administrator/?rappene

User: Rappe
Pass: Boss74206

Von: Ramil Valitov [mailto:notifications@github.com]
Gesendet: Freitag, 2. Juni 2017 10:24
An: rvalitov/widgetkit-popover-ex <widgetkit-popover-ex@noreply.github.com>
Cc: Oliver OM. Münch <oliver.muench@franz-mediaprint.de>; Author <author@noreply.github.com>
Betreff: Re: [rvalitov/widgetkit-popover-ex] Custom Toggle Image didn`t works (#6)


Hi! Please provide access to Joomla backend to ramilvalitov@gmail.com<mailto:ramilvalitov@gmail.com> , so that I can check the settings. Thank you!

**Comment by rvalitov** [comment]
Thanks. That's not a bug. You didn't specify the dimensions of the icons correctly, as a result, the browser couldn't parse that information.  The width and height of the markers must be specified using dimensions. You had:
![image](https://cloud.githubusercontent.com/assets/16267156/26719067/67a7dc74-4783-11e7-8e05-309c12be8cad.png)
Correct settings should be:
![image](https://cloud.githubusercontent.com/assets/16267156/26719091/79e45d40-4783-11e7-822d-f791627a18ff.png)

**Comment by ProjektOliver** [comment]
Sorry for my mistake! Have a nice Weekend.

LG
Oliver

Von: Ramil Valitov [mailto:notifications@github.com]
Gesendet: Freitag, 2. Juni 2017 11:07
An: rvalitov/widgetkit-popover-ex <widgetkit-popover-ex@noreply.github.com>
Cc: Oliver OM. Münch <oliver.muench@franz-mediaprint.de>; Author <author@noreply.github.com>
Betreff: Re: [rvalitov/widgetkit-popover-ex] Custom Toggle Image didn`t works (#6)


Thanks. That's not a bug. You didn't specify the dimensions of the icons correctly, as a result, the browser couldn't parse that information. The width and height of the markers must be specified using dimensions. You had:
[image]<https://cloud.githubusercontent.com/assets/16267156/26719067/67a7dc74-4783-11e7-8e05-309c12be8cad.png>
Correct settings should be:
[image]<https://cloud.githubusercontent.com/assets/16267156/26719091/79e45d40-4783-11e7-822d-f791627a18ff.png>
