### ISSUE TITLE
Blank page after upgrade popover-ex

### ISSUE THREAD

**Issue by fanfouet** [rvalitov/widgetkit-popover-ex#7]
Hi rvalitov,

first thank for yours great plugin :)

Joomla 3.7.5 - yootheme Peak - Widgetkit 2.9.3 - alls are uptodate

I have blank page - admin & frontpage - after upgrade popover-ex plugin

Have you any idea why ? 

Everything working when iu replace with older version

Many thanks inb advance for yours help

Kind regards,
francois

**Comment by rvalitov** [comment]
Bonjour François,
What version of PopoverEx works? Can you share the error.log file of Apache?

**Comment by fanfouet** [comment]
As much for me, the problem came that I had made a bcopie of the plugin named _popoverex-copy .. I suppressed everything works ..
Thank you, have an nice day

` Fatal error: Cannot declare class WidgetkitEx\PopoverEx\WKDiskItem, because the name is already in use in /home/clients/4ce05ae560faf6509b084fb52c790f72/web/new/administrator/components/com_widgetkit/plugins/widgets/popover_ex/views/WidgetkitExPlugin.php on line 18`
